/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#0F1113',
        surface: '#111417',
        'surface-dim': '#111417',
        'surface-bright': '#36393e',
        'surface-container-lowest': '#0b0e12',
        'surface-container-low': '#191c20',
        'surface-container': '#1d2024',
        'surface-container-high': '#272a2e',
        'surface-container-highest': '#323539',
        'on-surface': '#e1e2e8',
        'on-surface-variant': '#c6c5d1',
        'inverse-surface': '#e1e2e8',
        'inverse-on-surface': '#2e3135',
        outline: '#90909a',
        'outline-variant': '#45464f',
        'surface-tint': '#b9c3ff',
        primary: '#cbd2ff',
        'on-primary': '#212c61',
        'primary-container': '#aab5f3',
        'on-primary-container': '#3a457b',
        'inverse-primary': '#505b93',
        secondary: '#9ad2c3',
        'on-secondary': '#00382e',
        'secondary-container': '#195247',
        'on-secondary-container': '#8cc3b5',
        tertiary: '#d1d0ff',
        'on-tertiary': '#1000a9',
        'tertiary-container': '#b0b2ff',
        'on-tertiary-container': '#3131c1',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'surface-variant': '#323539',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '2px',
        DEFAULT: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        full: '9999px',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.5s ease forwards',
        'slide-up': 'slideUp 0.5s ease forwards',
        'counter': 'counter 2s ease-out forwards',
      },
      keyframes: {
        fadeIn: { from: { opacity: 0 }, to: { opacity: 1 } },
        slideUp: { from: { opacity: 0, transform: 'translateY(20px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
      },
      backdropBlur: { xs: '2px' },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #cbd2ff 0%, #9ad2c3 100%)',
        'gradient-radial': 'radial-gradient(ellipse at center, var(--tw-gradient-stops))',
      },
      boxShadow: {
        'glow-primary': '0 0 20px rgba(203,210,255,0.2)',
        'glow-secondary': '0 0 20px rgba(154,210,195,0.2)',
      },
    },
  },
  plugins: [],
}
